"""Adiciona tabela Assessment para avaliações

Revision ID: 003b2b2e3d61
Revises: 20f31c2b9486
Create Date: 2025-06-28 19:08:50.968497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003b2b2e3d61'
down_revision = '20f31c2b9486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('main_complaint', sa.Text(), nullable=True),
    sa.Column('history_of_present_illness', sa.Text(), nullable=True),
    sa.Column('past_medical_history', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('social_history', sa.Text(), nullable=True),
    sa.Column('inspection_notes', sa.Text(), nullable=True),
    sa.Column('palpation_notes', sa.Text(), nullable=True),
    sa.Column('mobility_assessment', sa.Text(), nullable=True),
    sa.Column('strength_assessment', sa.Text(), nullable=True),
    sa.Column('neuro_assessment', sa.Text(), nullable=True),
    sa.Column('functional_assessment', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment')
    # ### end Alembic commands ###
