"""Implementa financeiro detalhado nos agendamentos

Revision ID: 0215282bdeb5
Revises: 08c462e7d484
Create Date: 2025-06-29 00:13:28.787905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0215282bdeb5'
down_revision = '08c462e7d484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_notes', sa.Text(), nullable=True))
        batch_op.drop_column('payment_status')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('payment_notes')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('session_price')

    # ### end Alembic commands ###
