"""Adiciona campos financeiros a agendamentos

Revision ID: 08c462e7d484
Revises: 570db570e21f
Create Date: 2025-06-28 23:19:01.899095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c462e7d484'
down_revision = '570db570e21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
