"""Adiciona campo de subscrição à clínica

Revision ID: 183cff3b0bb6
Revises: fd55049e4950
Create Date: 2025-06-30 19:44:27.688860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183cff3b0bb6'
down_revision = 'fd55049e4950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mp_subscription_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_clinic_mp_subscription_id'), ['mp_subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_mp_subscription_id'))
        batch_op.drop_column('mp_subscription_id')

    # ### end Alembic commands ###
