"""Adiciona ID de cliente do Mercado Pago à clínica

Revision ID: 2201ba767c0a
Revises: 149cf0fde108
Create Date: 2025-07-03 00:19:50.071179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2201ba767c0a'
down_revision = '149cf0fde108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mp_customer_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_clinic_mp_customer_id'), ['mp_customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_mp_customer_id'))
        batch_op.drop_column('mp_customer_id')

    # ### end Alembic commands ###
