"""Altera sistema para passe de acesso com data de expiração

Revision ID: 54c4fb659f04
Revises: 2201ba767c0a
Create Date: 2025-07-05 01:31:46.035751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c4fb659f04'
down_revision = '2201ba767c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_expires_on', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_clinic_mp_customer_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_mp_subscription_id'))
        batch_op.drop_column('mp_customer_id')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('mp_subscription_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mp_subscription_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('mp_customer_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_clinic_mp_subscription_id'), ['mp_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_mp_customer_id'), ['mp_customer_id'], unique=False)
        batch_op.drop_column('access_expires_on')

    # ### end Alembic commands ###
