"""Adicionando campo created_at em Patient

Revision ID: 87e4d4b841a2
Revises: 5ab35b9945bb
Create Date: 2025-06-28 14:18:28.109053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e4d4b841a2'
down_revision = '5ab35b9945bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
