"""Adiciona campo de especialidade ao paciente

Revision ID: a0ec0760db86
Revises: ad9ec59f59ce
Create Date: 2025-06-28 20:40:02.480962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ec0760db86'
down_revision = 'ad9ec59f59ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###
