"""Adiciona tabela UploadedFile para uploads

Revision ID: ad9ec59f59ce
Revises: 003b2b2e3d61
Create Date: 2025-06-28 19:48:33.723542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9ec59f59ce'
down_revision = '003b2b2e3d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('secure_url', sa.String(length=512), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('electronic_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_diagnosis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_record', schema=None) as batch_op:
        batch_op.drop_column('medical_diagnosis')

    op.drop_table('uploaded_file')
    # ### end Alembic commands ###
