"""Adiciona campos do Stripe à clínica

Revision ID: bc8a606e3231
Revises: 183cff3b0bb6
Create Date: 2025-07-01 10:56:08.779867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8a606e3231'
down_revision = '183cff3b0bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_clinic_mp_subscription_id'))
        batch_op.drop_column('mp_subscription_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mp_subscription_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_clinic_mp_subscription_id'), ['mp_subscription_id'], unique=False)
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
